name: Prettier-Linter

on:
    pull_request:
        branches: [master]

jobs:
    prettier:
        name: Lint code base
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Run Prettier Linter
              uses: creyD/prettier_action@v4.3
              with:
                  commit_message: 'action: Prettified Code'
